### ISSUE TITLE
In order to give the best experience to the customer as a Relationship Manager i want having a best suitable system.

### ISSUE THREAD

**Issue by levutung02** [liamlindsay9/ISDM-Group-3#5]

**Comment by liamlindsay9** [comment]
I have included attributes to ensure RM's, and both types of customers(In and Out Bound) have information that would allow service from the RM's to be tailored to the customers as best as possible. RM's have a specialized_location attribute, Out-Bound and In-Bound customers both have a holiday_preference attribute to allow for effective pairing.
